name: maps39
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.21.1
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - holoviews=1.15.4
  - hvplot=0.8.3
  - matplotlib-base=3.7.1
  - pandas=2.0.1
  - pip=23.1.2
  - pip:
    - streamlit==1.22.0